export default defineNitroConfig({
  compatibilityDate: '2026-02-23',
  srcDir: 'server',
  ignore: ['test/**', '**/*.test.ts'],
  experimental: {
    tasks: true,
  },
  scheduledTasks: {
    '*/30 * * * * *': ['trading:cycle'],
  },
  runtimeConfig: {
    krakenApiKey: '',
    krakenPrivateKey: '',
    apiToken: '',
    gridLowerPrice: '',
    gridUpperPrice: '',
    gridLevels: '',
    orderSizeUsdc: '',
    sandboxMode: '',
    postOnly: '',
    gridRecentering: '',
    volatilityEnabled: '',
    atrPeriod: '',
    spacingMinMultiplier: '',
    spacingMaxMultiplier: '',
    stopLossPercent: '',
    takeProfitUsdc: '',
    sentryDsn: '',
  },
  storage: {
    grid: { driver: 'fs', base: './.data/db/grid' },
    orders: { driver: 'fs', base: './.data/db/orders' },
    trades: { driver: 'fs', base: './.data/db/trades' },
    snapshots: { driver: 'fs', base: './.data/db/snapshots' },
    'migration-meta': { driver: 'fs', base: './.data/db/migration-meta' },
  },
})
